name: Setup
description: Setup project

runs:
  using: composite
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@f4d14e03ff726c06358e5557344e1da148b56cf7 # v1

    - name: Install dependencies
      shell: bash
      run: bun install
