name: Setup
description: Setup project

runs:
  using: composite
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@123c6c4e2fea3eb7bffaa91a85eb6b3d505bf7af # v2

    - name: Install dependencies
      shell: bash
      run: bun install
