name: Setup
description: Setup project

runs:
  using: composite
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2

    - name: Install dependencies
      shell: bash
      run: bun install
