name: Setup
description: Setup project

runs:
  using: composite
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2

    - name: Install dependencies
      shell: bash
      run: bun install
