import { createPagesFunctionHandler } from "@remix-run/cloudflare-pages";

// biome-ignore lint/style/noNamespaceImport: 公式に則る
// @ts-ignore
import * as build from "../build/server";
import { getLoadContext } from "../load-context";

// @ts-ignore - the server build file is generated by `remix vite:build`
export const onRequest = createPagesFunctionHandler({ build, getLoadContext });
