// Generated by Wrangler on Thu Apr 04 2024 06:38:28 GMT+0900 (Japan Standard Time)
// by running `wrangler types`

// biome-ignore lint/correctness/noUnusedVariables: .d.tsファイルのため
interface Env {
  // biome-ignore lint/style/useNamingConvention: 慣習のため
  DB: D1Database;
}
