// Generated by Wrangler on Fri Apr 05 2024 07:17:43 GMT+0900 (Japan Standard Time)
// by running `wrangler types`

interface Env {
	dot_strive_session_kv: KVNamespace;
	SESSION_SECRET: string;
	DB: D1Database;
}
