// Generated by Wrangler on Fri Apr 05 2024 12:00:15 GMT+0900 (Japan Standard Time)
// by running `wrangler types`

interface Env {
	dot_strive_session_kv: KVNamespace;
	SESSION_SECRET: string;
	GOOGLE_AUTH_CLIENT_ID: string;
	GOOGLE_AUTH_CLIENT_SECRET: string;
	DB: D1Database;
}
